# Uncomment this line to define a global platform for your project
 platform :ios, '8.1'
target 'KangLeBao' do
  pod 'AFNetworking', '~> 3.0.4'
  pod 'FBDTools', '~> 0.0.4'
  pod 'Masonry', '~> 1.0.1'
  pod 'FMDBTool'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'MJRefresh', '~> 3.1.12'

end
